/**
 * Short descriptions for every nav item -- displayed in the Customize page grid.
 * Keys are route paths (matching nav-items.ts). One sentence, 10 words each max.
 */
export const NAV_DESCRIPTIONS: Record<string, string> = {
  // Main items
  '/': 'Start or continue an AI conversation',
  '/dashboard': 'Overview of your tasks, notes, and agents',
  '/analytics': 'Usage costs, token counts, and model stats',
  '/channels': 'Connected messaging channels and integrations',
  '/history': 'Browse and search past conversations',

  // Personal Data
  '/tasks': 'Create, track, and complete your tasks',
  '/notes': 'Capture and organize your notes',
  '/calendar': 'View and manage calendar events',
  '/contacts': 'Store and browse your contacts',
  '/bookmarks': 'Save and organize important links',
  '/expenses': 'Track your spending and expenses',
  '/habits': 'Build and track daily habits',
  '/pomodoro': 'Focus timer with Pomodoro technique',

  // AI & Automation
  '/memories': 'Long-term facts the AI remembers about you',
  '/goals': 'Set and track personal or project goals',
  '/plans': 'AI-generated step-by-step action plans',
  '/triggers': 'Automate actions on events or schedules',
  '/workflows': 'Build and run multi-step automations',
  '/autonomous': 'Manage background AI agents',
  '/artifacts': 'Outputs and files generated by AI',
  '/approvals': 'Review and approve pending AI actions',
  '/autonomy': 'Configure AI autonomy and trust levels',

  // Tools & Extensions
  '/tools': 'Browse available AI tools and functions',
  '/custom-tools': 'Define your own JavaScript AI tools',
  '/skills': 'Install and manage skill packages',
  '/plugins': 'Extend OwnPilot with community plugins',

  // System
  '/agents': 'Configure and manage AI agent profiles',
  '/models': 'View and test available AI models',
  '/wizards': 'Guided setup flows for new features',
  '/workspaces': 'Manage file and project workspaces',
  '/custom-data': 'Define and query your custom data types',
  '/data-browser': 'Inspect raw data tables in your database',
  '/costs': 'Track AI usage costs and budgets',
  '/logs': 'View system and agent activity logs',
  '/event-monitor': 'Monitor real-time system events',

  // Experimental
  '/claws': 'Autonomous continuous AI agent runners',
  '/edge-devices': 'Manage IoT and edge device connections',
  '/coding-agents': 'AI agents that write and run code',
  '/orchestration': 'Coordinate complex multi-agent tasks',

  // Settings
  '/settings/api-keys': 'Manage your LLM provider API keys',
  '/settings/providers': 'Configure AI provider connections',
  '/settings/ai-models': 'Set default and fallback AI models',
  '/settings/model-routing': 'Route tasks to the best model automatically',
  '/settings/security': 'Password, auth, and access control',
  '/settings/security-scanner': 'Scan for security vulnerabilities',
  '/settings/tool-groups': 'Organize tools into permission groups',
  '/settings/cli-tools': 'Register CLI tools for AI use',
  '/settings/coding-agents': 'Configure coding agent environments',
  '/settings/mcp-servers': 'Connect Model Context Protocol servers',
  '/settings/connected-apps': 'Link external apps and services',
  '/settings/workflow-tools': 'Tools available inside workflow nodes',
  '/settings/config-center': 'Global OwnPilot configuration',
  '/settings/system': 'System info, storage, and diagnostics',

  // Bottom items
  '/about': 'About OwnPilot, version, and credits',
  '/profile': 'Your profile, preferences, and account',
};
