/**
 * Route exports
 */

export { healthRoutes } from './health.js';
export { agentRoutes, getAgent, getOrCreateDefaultAgent } from './agents.js';
export { chatRoutes } from './chat/index.js';
export { toolsRoutes } from './tools.js';
export { settingsRoutes } from './settings.js';
export { channelRoutes } from './channels/index.js';
export { costRoutes } from './costs.js';
export { modelsRoutes } from './models.js';
export { providersRoutes } from './providers.js';
export { profileRoutes } from './profile.js';
export { personalDataRoutes } from './personal-data.js';
export { customDataRoutes } from './custom-data.js';
export { memoriesRoutes } from './memories.js';
export { goalsRoutes } from './goals.js';
export { triggersRoutes } from './triggers.js';
export { plansRoutes } from './plans.js';
export { autonomyRoutes } from './autonomy.js';
export { auditRoutes } from './audit.js';
export { workspaceRoutes } from './workspaces.js';
export { fileWorkspaceRoutes } from './file-workspaces.js';
export { pluginsRoutes } from './plugins.js';
export { productivityRoutes } from './productivity.js';

export { modelConfigsRoutes } from './model-configs.js';
export { dashboardRoutes } from './dashboard.js';
export { customToolsRoutes } from './custom-tools.js';
export { databaseRoutes } from './database.js';
export { expensesRoutes } from './expenses.js';
export { configServicesRoutes } from './config-services.js';
export { localProvidersRoutes } from './local-providers.js';
export { channelAuthRoutes } from './channels/auth.js';
export { debugRoutes } from './debug.js';
export { executionPermissionsRoutes } from './execution-permissions.js';
export { heartbeatsRoutes } from './heartbeats.js';
export { extensionsRoutes } from './extensions.js';
export { mcpRoutes } from './mcp.js';
export { webhookRoutes } from './webhooks.js';
export { workflowRoutes } from './workflows.js';
export { composioRoutes } from './composio.js';
export { uiAuthRoutes } from './ui-auth.js';
export { modelRoutingRoutes } from './model-routing.js';
export { codingAgentsRoutes } from './coding-agents.js';
export { cliProvidersRoutes } from './cli-providers.js';
export { cliToolsRoutes } from './cli-tools.js';
export { securityRoutes } from './security.js';
export { bridgeRoutes } from './bridges.js';
export { artifactsRoutes } from './artifacts.js';
export { voiceRoutes } from './voice.js';
export { browserRoutes } from './browser.js';
export { skillsRoutes } from './skills.js';
export { edgeRoutes } from './edge.js';
export { soulRoutes } from './souls.js';
export { crewRoutes } from './crews.js';
export { agentMessageRoutes } from './agent-messages.js';
export { heartbeatLogRoutes } from './heartbeat-logs.js';
export { agentCommandCenterRoutes } from './agent-command-center.js';
export { cliChatRoutes } from './cli-chat.js';
export { notificationRoutes } from './notifications.js';
export { clawRoutes } from './claws.js';
export { pulseRoutes } from './pulse.js';
export { tunnelRoutes } from './tunnel.js';
